blank_issues_enabled: true
contact_links:
  - name: Get in touch with the developer
    url: https://sammcnab.co.uk/contact
    about: Please do NOT use this email to post issues or feature requests (only important business/personal contact).
