import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Lecturer - Simulation & Immersive Technologies',
    company: 'University of West London',
    company_legal_name: 'UWL',
    logo: '/images/careers/uwl.png',
    location: 'London, United Kingdom 🇬🇧',
    location_type: 'On-Site',
    type: 'Full-time',
    start_date: '2023-04',
    end_date: null,
    industry: 'higher-education',
    link: 'https://uwl.ac.uk',
    responsibilities: [
      'Design & Implementation of Paramedic & Nursing curriculum, specialising in Simulation & Immersive Technologies.',
      'Work on several applications & systems across the university, including a facility booking system, student portal, and other internal systems.',
      'Teaching & Assessment of Paramedic & Nursing students in Simulation & Immersive Technologies.',
    ],
  },
  {
    position: 'Module Lead - Year 3 & 4 Nursing Practice',
    company: 'University of West London',
    company_legal_name: 'UWL',
    logo: '/images/careers/uwl.png',
    location: 'London, United Kingdom 🇬🇧',
    location_type: 'On-Site',
    type: 'Full-time',
    start_date: '2024-11',
    end_date: null,
    industry: 'higher-education',
    link: 'https://uwl.ac.uk',
    responsibilities: [
      'Design & Implementation of Nursing curriculum, focussed on pre-placement preparation',
      'Supporting and guiding students through the modules and their placement time to ensure students are comfortable and operating effectively.',
    ],
  },
  {
    position: 'Module Lead - BNurs(Hons) Nursing Practice',
    company: 'University of West London',
    company_legal_name: 'UWL',
    logo: '/images/careers/uwl.png',
    location: 'London, United Kingdom 🇬🇧',
    location_type: 'On-Site',
    type: 'Full-time',
    start_date: '2023-04',
    end_date: '2024-11',
    industry: 'higher-education',
    link: 'https://uwl.ac.uk',
    responsibilities: [
      'Design & Implementation of Nursing curriculum, focussed on pre-placement preparation',
      'Supporting and guiding students through the modules and their placement time to ensure students are comfortable and operating effectively.',
    ],
  },
  {
    position: 'Registered Paramedic & Clinical Trainer',
    company: 'Self Employed',
    company_legal_name: 'SMedical',
    logo: '/images/careers/my-avatar.png',
    location: 'United Kingdom 🇬🇧',
    location_type: 'Hybrid',
    type: 'Self Employed',
    start_date: '2022-02',
    end_date: null,
    industry: 'education, healthcare',
    link: 'https://sammcnab.co.uk',
    responsibilities: [
      'Deliver training to healthcare professionals in a variety of clinical skills, including airway management, resuscitation, and trauma care.',
      'Design & deliver bespoke training packages to meet the needs of individual clients.',
      'Provide clinical support to a range of clients, including care homes, schools, and private individuals.',
    ],
  },
  {
    position: 'Member of Palliative & End of Life Care SIG',
    company: 'College of Paramedics',
    company_legal_name: 'CoP',
    logo: '/images/certs/collegeofparamedics_logo.jpeg',
    location: 'United Kingdom 🇬🇧',
    location_type: 'Remote',
    type: 'Contract',
    start_date: '2022-06',
    end_date: null,
    industry: 'education, healthcare',
    link: 'https://collegeofparamedics.co.uk/',
    responsibilities: [
      'Provide invaluable insight into the unique challenges and opportunities encountered by paramedics working in palliative and end-of-life care.',
      'Serving as a liaison between paramedics working in palliative and end-of-life care settings and the College, providing a platform for them to voice their views, ideas, and concerns.',
      'Supporting wider activities of the CoP, including the review of national e-learning modules.',
    ],
  },
  {
    position: 'Article Reviewer',
    company: 'International Journal of Healthcare Simulation',
    company_legal_name: 'IJoHS',
    logo: '/images/careers/ijohs_logo.jpeg',
    location: 'United Kingdom 🇬🇧',
    location_type: 'Remote',
    type: 'Contract',
    start_date: '2024-07',
    end_date: null,
    industry: 'education, healthcare',
    link: 'https://www.ijohs.com/',
    responsibilities: [
      'Critically analysing manuscripts, providing constructive feedback, and making recommendations for publication.',
      'Collaborating closely with editors and authors to enhance the scientific rigour and impact of research in the field of healthcare simulation.',
    ],
  },
  {
    position: 'Combat Medical Technician (Paramedic)',
    company: 'HM Armed Forces',
    company_legal_name: 'British Army',
    logo: '/images/careers/british_army_logo.jpeg',
    location: 'United Kingdom 🇬🇧',
    location_type: 'Hybrid',
    type: 'Part Time',
    start_date: '2022-02',
    end_date: '2024-04',
    industry: 'education, healthcare',
    link: 'https://www.army.mod.uk/',
    responsibilities: [
      'Provide pre-hospital emergency care to military personnel in the UK and overseas.',
      'Train and mentor junior medics in clinical skills and military knowledge.',
      'Deploy on operations to provide medical support to troops in the field.',
    ],
  },
  {
    position: 'Combat Medical Technician',
    company: 'HM Armed Forces',
    company_legal_name: 'British Army',
    logo: '/images/careers/british_army_logo.jpeg',
    location: 'United Kingdom 🇬🇧',
    location_type: 'Hybrid',
    type: 'Part Time',
    start_date: '2016-07',
    end_date: '2022-02',
    industry: 'education, healthcare',
    link: 'https://www.army.mod.uk/',
    responsibilities: [
      'Provide pre-hospital emergency care to military personnel in the UK and overseas.',
      'Train and mentor junior medics in clinical skills and military knowledge.',
      'Deploy on operations to provide medical support to troops in the field.',
    ],
  },
  {
    position: 'Statutory & Mandatory Trainer',
    company: 'HCRG Care Group',
    company_legal_name: 'HCRG Care Group Ltd.',
    logo: '/images/careers/hcrg_logo.jpeg',
    location: 'United Kingdom 🇬🇧',
    location_type: 'Hybrid',
    type: 'Contract',
    start_date: '2023-01',
    end_date: '2023-06',
    industry: 'education, healthcare',
    link: 'https://www.hcrgcaregroup.com/',
    responsibilities: [
      'Deliver statutory & mandatory training to healthcare professionals in a variety of clinical skills, including airway management, resuscitation, and trauma care.',
      'Design & deliver bespoke training packages to meet the needs of individual clients.',
      'Provide clinical support to a range of clients, including care homes, schools, and private individuals.',
    ],
  },
  {
    position: 'Emergency Medical Technician',
    company: 'LAS',
    company_legal_name: 'London Ambulance Service',
    logo: '/images/careers/las_logo.jpeg',
    location: 'London, United Kingdom 🇬🇧',
    location_type: 'On-Site',
    type: 'Full-time',
    start_date: '2018-12',
    end_date: '2023-02',
    industry: 'healthcare',
    link: 'https://www.londonambulance.nhs.uk/',
    responsibilities: [
      'Provide pre-hospital emergency care to patients in London.',
      'Work as part of a team to deliver high-quality clinical care to patients in a variety of settings.',
      'Train and mentor junior staff in clinical skills and patient care.',
    ],
  },
  {
    position: 'Event Medic',
    company: 'Prometheus AlphaMed',
    company_legal_name: 'Prometheus AlphaMed Ltd.',
    logo: '/images/careers/prometheus_alphamed_logo.png',
    location: 'Scotland 🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    location_type: 'On-Site',
    type: 'Contract',
    start_date: '2017-09',
    end_date: '2018-12',
    industry: 'healthcare',
    link: 'https://www.prometheusalphamed.com/',
    responsibilities: [
      'Provide medical cover at events across Scotland, including music festivals, sports events, and corporate functions.',
      'Work as part of a team to deliver high-quality clinical care to patients in a variety of settings.',
      'Train and mentor junior staff in clinical skills and patient care.',
    ],
  },
  {
    position: 'Care Assistant',
    company: 'Erskine',
    company_legal_name: 'Erskine Care Homes',
    logo: '/images/careers/erskine_logo.jpeg',
    location: 'Edinburgh, Scotland 🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    location_type: 'On-Site',
    type: 'Full-time',
    start_date: '2017-10',
    end_date: '2018-04',
    industry: 'healthcare',
    link: 'https://www.erskine.org.uk/',
    responsibilities: [
      'Provide personal care to residents in a care home setting.',
      'Support residents with their daily activities, including eating, washing, and dressing.',
      'Work as part of a team to deliver high-quality care to residents.',
    ],
  },
  {
    position: 'Lighting Designer | Technician | Project Manager',
    company: 'Self Employed',
    company_legal_name: 'Self Employed',
    logo: '/images/careers/my-avatar.png',
    location: 'United Kingdom 🇬🇧',
    location_type: 'Hybrid',
    type: 'Self Employed',
    start_date: '2013-06',
    end_date: '2018-09',
    industry: 'theatre, events',
    link: 'https://sammcnab.co.uk',
    responsibilities: [
      'Design & implement lighting for a variety of events, including theatre productions, music concerts, and corporate functions.',
      'Manage projects from concept to completion, including budgeting, scheduling, and client liaison.',
      'Work as part of a team to deliver high-quality lighting solutions to clients.',
    ],
  },
  {
    position: 'Swing Technician @ Cowgate',
    company: 'Underbelly',
    company_legal_name: 'Underbelly Ltd.',
    logo: '/images/careers/underbelly_logo.jpeg',
    location: 'Edinburgh, Scotland 🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    location_type: 'On-Site',
    type: 'Contract',
    start_date: '2016-07',
    end_date: '2016-08',
    industry: 'theatre',
    link: 'https://www.underbelly.co.uk/',
    responsibilities: [
      'Provide technical support to a variety of shows at the Edinburgh Festival Fringe.',
      'Work as part of a team to deliver high-quality technical solutions to clients.',
      'Train and mentor junior staff in technical skills and customer service.',
    ],
  },
  {
    position: 'Returns Supervisor',
    company: 'Blue Parrot',
    company_legal_name: 'Blue Parrot Ltd.',
    logo: '/images/careers/blueparrot_production__events_logo.jpeg',
    location: 'Edinburgh, Scotland 🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    location_type: 'On-Site',
    type: 'Full-time',
    start_date: '2015-05',
    end_date: '2016-07',
    industry: 'theatre',
    link: 'https://blueparrotevents.com',
    responsibilities: [
      'Manage the returns department for a busy event production company.',
      'Supervise a team of staff to ensure the smooth running of the department.',
      'Work with clients to resolve any issues with their orders and ensure customer satisfaction.',
    ],
  },
];
