import { CertProps } from '../types/certs';

export const CERTS: CertProps[] = [
  {
    membership: 'Member of the Chartered Management Institute (CMgr MCMI)',
    organisation: 'Chartered Management Institute',
    logo: '/images/certs/charteredmanagementinstitute_logo.jpeg',
    type: 'Membership',
    start_date: '2024-05',
    end_date: null,
    industry: 'leadership, management, education',
    link: 'https://www.cmi.org.uk',
    description: [
      'Chartered Manager is the highest status that can be achieved in the management profession. It is a status only awarded by CMI and is recognised and valued across all sectors.',
    ],
  },
  {
    membership: 'Member of the Institute of Leadership (MIoL)',
    organisation: 'Institute of Leadership',
    logo: '/images/certs/instituteofleadership_logo.jpeg',
    type: 'Membership',
    start_date: '2024-05',
    end_date: null,
    industry: 'leadership, management, education',
    link: 'https://www.instituteforleadership.org.uk',
    description: [
      'The Institute of Leadership is a professional body for leaders, managers and coaches. It is a not-for-profit organisation that exists to raise the standard of leadership and management in the UK.',
    ],
  },
  {
    membership: 'Professional Member (MBCS)',
    organisation: 'British Computer Society',
    logo: '/images/certs/britishcomputersociety_logo.jpeg',
    type: 'Membership',
    start_date: '2024-01',
    end_date: null,
    industry: 'information technology',
    link: 'https://www.bcs.org',
    description: [
      'The British Computer Society is the Chartered Institute for IT. It champions the global IT profession and the interests of individuals engaged in that profession for the benefit of all.',
    ],
  },
  {
    membership: 'Registered Science Technician (RSciTech)',
    organisation: 'Science Council',
    logo: '/images/certs/sciencecouncil_logo.jpeg',
    type: 'Membership',
    start_date: '2024-01',
    end_date: null,
    industry: 'healthcare',
    link: 'https://www.sciencecouncil.org',
    description: [
      'The Science Council is a membership organisation that brings together learned societies, professional institutions, universities and businesses to represent the UK science workforce.',
    ],
  },
  {
    membership: 'CS50: Introduction to Computer Science',
    organisation: 'Harvard University',
    logo: '/images/certs/harvard_logo.jpeg',
    type: 'Certification',
    start_date: '2024-02',
    end_date: null,
    industry: 'information technology',
    link: 'https://www.edx.org/course/cs50s-introduction-to-computer-science',
    description: [
      'CS50 is Harvard University’s introduction to the intellectual enterprises of computer science and the art of programming. It is a free online course that teaches students how to think algorithmically and solve problems efficiently.',
    ],
  },
  {
    membership: 'Individual Member',
    organisation: 'Association for Simulated Practice in Healthcare',
    logo: '/images/certs/aspih_logo.jpeg',
    type: 'Membership',
    start_date: '2023-08',
    end_date: null,
    industry: 'healthcare, education, simulation',
    link: 'https://www.aspih.org.uk',
    description: [
      'ASPiH is a not-for-profit membership association dedicated to improving patient care and professional performance by the use of simulated practice and technology-enhanced learning.',
    ],
  },
  {
    membership: 'CompTIA A+ (A+)',
    organisation: 'CompTIA',
    logo: '/images/certs/comptia_logo.jpeg',
    type: 'Certification',
    start_date: '2023-02',
    end_date: null,
    industry: 'information technology',
    link: 'https://www.comptia.org/certifications/a',
    description: [
      'CompTIA A+ is the preferred qualifying credential for technical support and IT operational roles. It is about much more than PC repair. Candidates are better prepared to troubleshoot and problem solve.',
    ],
  },
  {
    membership: 'Level 3 Award in Effective Coaching',
    organisation: 'City & Guilds',
    logo: '/images/certs/cityandguilds_logo.jpeg',
    type: 'Qualification',
    start_date: '2023-02',
    end_date: null,
    industry: 'education',
    link: 'https://www.cityandguilds.com',
    description: [
      'This qualification is designed for those who want to develop their coaching skills and knowledge to use in a variety of contexts. It is ideal for those who are new to coaching or who want to develop their skills in this area.',
    ],
  },
  {
    membership: 'Level 3 Award in Education and Training',
    organisation: 'City & Guilds',
    logo: '/images/certs/cityandguilds_logo.jpeg',
    type: 'Qualification',
    start_date: '2023-02',
    end_date: null,
    industry: 'education',
    link: 'https://www.cityandguilds.com',
    description: [
      'This qualification is designed for those who want to teach in the further education and skills sector. It is ideal for those who are new to teaching or who want to develop their skills in this area.',
    ],
  },
  {
    membership: 'CompTIA IT Fundamentals (ITF+)',
    organisation: 'CompTIA',
    logo: '/images/certs/comptia_logo.jpeg',
    type: 'Certification',
    start_date: '2022-11',
    end_date: null,
    industry: 'information technology',
    link: 'https://www.comptia.org/certifications/it-fundamentals',
    description: [
      'CompTIA IT Fundamentals (ITF+) is an introduction to basic IT knowledge and skills. It is ideal for those considering a career in IT or who work in an allied field that requires a broad understanding of IT.',
    ],
  },
  {
    membership: 'Member of College of Paramedics (MCPara)',
    organisation: 'College of Paramedics',
    logo: '/images/certs/collegeofparamedics_logo.jpeg',
    type: 'Membership',
    start_date: '2022-03',
    end_date: null,
    industry: 'healthcare',
    link: 'https://www.collegeofparamedics.co.uk',
    description: [
      'The College of Paramedics is the recognised professional body for paramedics in the UK. It is dedicated to promoting and advancing the paramedic profession.',
    ],
  },
  {
    membership: 'Registered Paramedic',
    organisation: 'Health and Care Professions Council',
    logo: '/images/certs/hcpc_logo.jpeg',
    type: 'Membership',
    start_date: '2022-03',
    end_date: null,
    industry: 'healthcare',
    link: 'https://www.hcpc-uk.org',
    description: [
      'The Health and Care Professions Council is a regulator for health, psychological and social work professionals. It maintains a register of professionals who meet its standards for their training, professional skills, behaviour and health.',
    ],
  },
  {
    membership: 'Level 4 Diploma, Associate Ambulance Practitioner',
    organisation: 'FutureQuals',
    logo: '/images/certs/futurequals_logo.jpeg',
    type: 'Qualification',
    start_date: '2020-07',
    end_date: null,
    industry: 'healthcare',
    link: 'https://futurequals.com',
    description: [
      'The Level 4 Diploma for Associate Ambulance Practitioners is designed to provide learners with the knowledge and skills required to work as an Associate Ambulance Practitioner. It is a qualification that is recognised by the NHS and the private ambulance sector.',
    ],
  },
  {
    membership: 'Level 3 Certificate in Emergency Response Ambulance Driving',
    organisation: 'FutureQuals',
    logo: '/images/certs/futurequals_logo.jpeg',
    type: 'Qualification',
    start_date: '2019-03',
    end_date: null,
    industry: 'healthcare',
    link: 'https://futurequals.com',
    description: [
      'The Level 3 Certificate in Emergency Response Ambulance Driving is designed to provide learners with the knowledge and skills required to drive an ambulance in an emergency response environment. It is a qualification that is recognised by the NHS and the private ambulance sector.',
    ],
  },
];
